import plugin from 'tailwindcss/plugin';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        on_primary: 'var(--on-primary)',
        'on-primary': 'var(--on-primary)',
        primary_container: 'var(--primary-container)',
        'primary-container': 'var(--primary-container)',
        on_primary_container: 'var(--on-primary-container)',
        'on-primary-container': 'var(--on-primary-container)',
        'primary-fixed': 'var(--primary-fixed)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',

        secondary: 'var(--secondary)',
        on_secondary: 'var(--on-secondary)',
        'on-secondary': 'var(--on-secondary)',
        secondary_container: 'var(--secondary-container)',
        'secondary-container': 'var(--secondary-container)',
        on_secondary_container: 'var(--on-secondary-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',

        tertiary: 'var(--tertiary)',
        on_tertiary: 'var(--on-tertiary)',
        'on-tertiary': 'var(--on-tertiary)',
        tertiary_container: 'var(--tertiary-container)',
        'tertiary-container': 'var(--tertiary-container)',
        on_tertiary_container: 'var(--on-tertiary-container)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',

        error: 'var(--error)',
        on_error: 'var(--on-error)',
        'on-error': 'var(--on-error)',
        error_container: 'var(--error-container)',
        'error-container': 'var(--error-container)',
        on_error_container: 'var(--on-error-container)',
        'on-error-container': 'var(--on-error-container)',

        background: 'var(--background)',
        on_background: 'var(--on-background)',
        'on-background': 'var(--on-background)',

        surface: 'var(--surface)',
        on_surface: 'var(--on-surface)',
        'on-surface': 'var(--on-surface)',
        surface_variant: 'var(--surface-variant)',
        'surface-variant': 'var(--surface-variant)',
        on_surface_variant: 'var(--on-surface-variant)',
        'on-surface-variant': 'var(--on-surface-variant)',
        surface_bright: 'var(--surface-bright)',
        'surface-bright': 'var(--surface-bright)',
        surface_dim: 'var(--surface-dim)',
        'surface-dim': 'var(--surface-dim)',
        surface_container_lowest: 'var(--surface-container-lowest)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        surface_container_low: 'var(--surface-container-low)',
        'surface-container-low': 'var(--surface-container-low)',
        surface_container: 'var(--surface-container)',
        'surface-container': 'var(--surface-container)',
        surface_container_high: 'var(--surface-container-high)',
        'surface-container-high': 'var(--surface-container-high)',
        surface_container_highest: 'var(--surface-container-highest)',
        'surface-container-highest': 'var(--surface-container-highest)',
        surface_tint: 'var(--surface-tint)',
        'surface-tint': 'var(--surface-tint)',
        inverse_surface: 'var(--inverse-surface)',
        'inverse-surface': 'var(--inverse-surface)',
        inverse_on_surface: 'var(--inverse-on-surface)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        inverse_primary: 'var(--inverse-primary)',
        'inverse-primary': 'var(--inverse-primary)',

        outline: 'var(--outline)',
        outline_variant: 'var(--outline-variant)',
        'outline-variant': 'var(--outline-variant)',
        foreground: 'var(--foreground)',
      },
      fontFamily: {
        sans: ['"Public Sans"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '32px',
        xl: '48px',
        gutter: '24px',
        'container-max': '1440px',
      },
      boxShadow: {
        card: '0px 2px 4px rgba(0, 0, 0, 0.05)',
      },
    },
  },
  plugins: [
    plugin(function({ addUtilities }) {
      addUtilities({
        '.text-headline-lg': {
          fontSize: '32px',
          fontWeight: '700',
        },
        '.text-headline-md': {
          fontSize: '24px',
          fontWeight: '700',
        },
        '.text-headline-sm': {
          fontSize: '20px',
          fontWeight: '600',
        },
        '.text-body-lg': {
          fontSize: '16px',
          fontWeight: '400',
        },
        '.text-body-md': {
          fontSize: '14px',
          fontWeight: '400',
        },
        '.text-label-bold': {
          fontSize: '12px',
          fontWeight: '700',
          letterSpacing: '0.05em',
        },
        '.text-label-md': {
          fontSize: '12px',
          fontWeight: '600',
        },
      });
    }),
  ],
};
